import { FontColor } from 'tuyun-utils';
const layers = [
  {
    id: 'POI_BG',
    type: 'symbol',
    source: 'layer-lv8',
    'source-layer': 'empty',
    paint: {
      'text-color': 'rgba(65, 65, 65, 0.9)',
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  {
    id: 'POI_LEVEL8',
    type: 'symbol',
    source: 'layer-lv8',
    'source-layer': 'POI_LEVEL_8',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 14,
      'icon-text-fit': 'both',
      'icon-text-fit-padding': [2, 4, 2, 4],
      'text-justify': 'center',
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
      'text-anchor': 'center',
      'text-keep-upright': false,
    },
    paint: {
      'text-color': 'rgba(65, 65, 65, 0.9)',
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
    maxzoom: 10,
  },
  //九级poi
  {
    id: 'POI_LEVEL_9_1107',
    type: 'symbol',
    source: 'layer-lv9',
    'source-layer': 'POI_LEVEL_9',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 11,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
    maxzoom: 10,
  },
  //10级poi
  {
    id: 'POI_LEVEL_10',
    type: 'symbol',
    source: 'layer-lv10',
    'source-layer': 'POI_LEVEL_10',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  //11级POI
  {
    id: 'POI_LEVEL_11_1108_1',
    type: 'symbol',
    source: 'layer-lv11',
    'source-layer': 'POI_LEVEL_11',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  // 12级POI
  {
    id: 'POI_LEVEL_12',
    type: 'symbol',
    source: 'layer-lv12',
    'source-layer': 'POI_LEVEL_12',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  // 13级POI
  {
    id: 'POI_LEVEL_13',
    type: 'symbol',
    source: 'layer-lv13',
    'source-layer': 'POI_LEVEL_13',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  // 14级POI
  {
    id: 'POI_LEVEL_14',
    type: 'symbol',
    source: 'layer-lv14',
    'source-layer': 'POI_LEVEL_14',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  // 15级POI 村庄和建筑物poi
  {
    id: 'SD_GAGNPT', // 此图层记录了村庄POI
    type: 'symbol',
    source: 'layer-lv15',
    'source-layer': 'SD_GAGNPT',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_shequ',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': 'rgb(89, 125, 155)',
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  //////////////////////////////////
  // poi
  {
    id: 'POI_LEVEL_15_1108',
    type: 'symbol',
    source: 'layer-lv15',
    'source-layer': 'POI_LEVEL_15',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  // 16级POI
  {
    id: 'POI_LEVEL_16_1108',
    type: 'symbol',
    source: 'layer-lv16',
    'source-layer': 'POI_LEVEL_16',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 12,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
  // 17级POI
  {
    id: 'POI_LEVEL_17_1108',
    type: 'symbol',
    source: 'layer-lv17',
    'source-layer': 'POI_LEVEL_17',
    layout: {
      'text-field': '{NAME}',
      visibility: 'visible',
      'symbol-placement': 'point',
      'text-size': 13,
      'text-padding': 4,
      'icon-image': 'ic_map_{KIND}',
      'text-justify': 'left',
      'text-anchor': 'left',
      'text-offset': [0.8, 0],
      'text-font': ['黑体'],
      'text-pitch-alignment': 'viewport',
      'text-rotation-alignment': 'viewport',
      'icon-rotation-alignment': 'viewport',
    },
    paint: {
      'text-color': ['get', ['get', 'KIND'], ['literal', FontColor]],
      'text-halo-width': 2,
      'text-halo-color': 'rgba(255, 255, 255, 1)',
    },
  },
];

export default layers;
